services:
  - type: web
    name: frigga-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: frigga-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health

databases:
  - name: frigga-db
    databaseName: frigga
    user: frigga_user 